In [20]:
In [1]: # PROCESAMIENTO 
    
# Se importan las librería numpy y las funciones de preprocesamiento
import numpy as np 
from sklearn import preprocessing

# Datos de prueba
input_data = np.array([[7.1, -4.1, 3.3],
[-3.2, 9.3, -7.1],
[5.7, 2.4, 2.1], 
[6.3, -9.7, -5.5]])
print(input_data)

[[ 7.1 -4.1  3.3]
 [-3.2  9.3 -7.1]
 [ 5.7  2.4  2.1]
 [ 6.3 -9.7 -5.5]]


In [21]:
# Binarizar los datos

data_binarized = preprocessing.Binarizer(threshold=3.1).transform(input_data)
print("\nDatos binarizados:\n", data_binarized)


Datos binarizados:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [22]:
# Imprimir la media y la desviación estándar

print("\nANTES:")
print("Media =", input_data.mean(axis=0))
print("Desviación estándar =", input_data.std(axis=0))


ANTES:
Media = [ 3.975 -0.525 -1.8  ]
Desviación estándar = [4.17215472 7.10717067 4.55521679]


In [23]:
# Remover la media

data_scaled = preprocessing.scale(input_data)
print("\nDESPUÉS:")
print("Media =", data_scaled.mean(axis=0))
print("Desviación estándar =", data_scaled.std(axis=0))


DESPUÉS:
Media = [ 2.77555756e-17 -1.11022302e-16  0.00000000e+00]
Desviación estándar = [1. 1. 1.]


In [24]:
# Escalamiento Min Max

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,
1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max escalamiento de datos:\n", data_scaled_minmax)


Min max escalamiento de datos:
 [[1.         0.29473684 1.        ]
 [0.         1.         0.        ]
 [0.86407767 0.63684211 0.88461538]
 [0.9223301  0.         0.15384615]]


In [25]:
# Normalización de datos

data_normalized_l1 = preprocessing.normalize(input_data,
norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data,
norm='l2')
print("\nL1 dato normalizado:\n", data_normalized_l1)
print("\nL2 dato normalizado:\n", data_normalized_l2)


L1 dato normalizado:
 [[ 0.48965517 -0.28275862  0.22758621]
 [-0.16326531  0.4744898  -0.3622449 ]
 [ 0.55882353  0.23529412  0.20588235]
 [ 0.29302326 -0.45116279 -0.25581395]]

L2 dato normalizado:
 [[ 0.80335043 -0.46390659  0.37338823]
 [-0.26380596  0.76668607 -0.58531947]
 [ 0.8726989   0.36745217  0.32152065]
 [ 0.49190236 -0.75737348 -0.42943857]]


In [26]:
# Manejo de etiquetas
import numpy as np
from sklearn import preprocessing

# Se definen algunas etiquetas simples
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow',
'white']

# Se crea un codificador de etiquetas y se ajustan las etiquetas
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

# Se imprime el mapeo entre palabras y números
print("\nMapeo de etiquetas:")
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)
    
# Codificar un conjunto de etiquetas con el codificador
test_labels = ['green', 'white', 'black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))

# Decodificar un conjunto de valores usando el codificador
encoded_values = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values)
print("Decoded labels =", list(decoded_list))


Mapeo de etiquetas:
black --> 0
green --> 1
red --> 2
white --> 3
yellow --> 4

Labels = ['green', 'white', 'black']
Encoded values = [1, 3, 0]

Encoded values = [3, 0, 4, 1]
Decoded labels = ['white', 'black', 'yellow', 'green']
